title: Atiqur Safayat
description: Portfolio of Atiqur Safayat — CSE Student, Developer & Tech Lead at Songjog Foundation
url: "https://atiqursafayat.github.io"
baseurl: ""

plugins:
  - jekyll-seo-tag
  - jekyll-sitemap

exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
  - README.md